notifications:
  email: false
language: ruby
rvm:
  - 2.6.2
cache:
  bundler: true
  directories:
    - vendor/bundle
    - $HOME/.rvm/gems
before_script:
  - bundle install
script:
  - bundle exec rubocop
